---
name: Deploy Flask App
on:
  workflow_dispatch: 
jobs:
  deploy:
    runs-on: self-hosted
    env:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
    steps:
    - name: Checking out  the Code
      uses: actions/checkout@v4
    - name: Deploy with Docker Compose
      run: docker-compose up -d --build --force-recreate

      #KEY TAKEAWAYS: Must be careful about runnina above docker compose command
      # The above force recreate command makes the containers work again n again

